FROM eos_boost:latest


WORKDIR /root
COPY chain33 chain33
COPY chain33-cli chain33-cli
COPY chain33-para-cli chain33-para-cli
COPY chain33.toml chain33*.toml ./
COPY entrypoint.sh entrypoint.sh
COPY relayd.toml relayd.toml
COPY relayd relayd
RUN mkdir -p wasm
COPY hello.abi ./wasm/hello.abi
COPY hello.wasm ./wasm/hello.wasm


CMD ["/root/chain33", "-f", "/root/chain33.toml"]

